export interface TextElementProps {
  name: string | number;
  conditions?: Array<any>;
  onBeforeCreate?: Function;
  onCreated?: Function;
  onBeforeMount?: Function;
  onMounted?: Function;
  onBeforeUpdate?: Function;
  onUpdated?: Function;
  onBeforeUnmount?: Function;
  onUnmounted?: Function;
  inline?: boolean;
  layout?: string | object | boolean;
  addClass?: Array<any> | object | string | Function;
  removeClass?: Array<any> | object | Function;
  replaceClass?: object | Function;
  overrideClass?: Array<any> | object | string | Function;
  addClasses?: object | Function;
  replaceClasses?: object | Function;
  removeClasses?: object | Function;
  overrideClasses?: object | Function;
  presets?: Array<any>;
  view?: string;
  views?: object;
  size?: string;
  columns?: object | string | number;
  templates?: object;
  description?: string | object;
  info?: string | object;
  infoPosition?: string;
  label?: string | object | Function;
  before?: object | string | number;
  between?: object | string | number;
  after?: object | string | number;
  slots?: object;
  onChange?: Function;
  formatData?: Function;
  formatLoad?: Function;
  submit?: boolean;
  rules?: Array<any> | string | object;
  messages?: object;
  fieldName?: string;
  type?: string;
  default?: string | number | object;
  debounce?: number;
  disabled?: boolean;
  floating?: string | boolean | object;
  id?: string;
  placeholder?: string | object;
  readonly?: boolean;
  inputType?: string;
  forceNumbers?: boolean;
  attrs?: object;
  addons?: object;
  autocomplete?: string | number;
  loading?: boolean;
  onBlur?: Function;
  onKeydown?: Function;
  onKeyup?: Function;
  onKeypress?: Function;
}
